import type { Metadata } from 'next'
import { Inter, Gelasio } from 'next/font/google'
import './globals.css'
import Script from 'next/script'
import '@fortawesome/fontawesome-svg-core/styles.css'
import { config } from '@fortawesome/fontawesome-svg-core'
config.autoAddCss = false

//--------------------------------------
//* USE NEXT/FONTS TO CONFIGURE FONTS
//--------------------------------------
const inter = Inter({ subsets: ['latin'] })

//--------------------------------------
//* CONFIGURE METADATA
//--------------------------------------
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

//--------------------------------------
//* RENDER THE PAGE
//--------------------------------------
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Script
        src="https://kit.fontawesome.com/41b8227a54.js"
        crossOrigin="anonymous"
      />
      <body className={`${inter.className} light`}>{children}</body>
    </html>
  )
}
